lib/shortage_web/router.ex
defmodule ShortageWeb.Router do
  use ShortageWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  scope "/", ShortageWeb do
    pipe_through :browser

    get "/", PageController, :index

    # TODO: Except "index" (useful for debugging)
    resources "/links", LinkController, except: [:edit, :update]

    get "/:shortened", ShortenedController, :show
  end
end

lib/shortage/application.ex
defmodule Shortage.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    # List all child processes to be supervised
    children = [
      # Start the Ecto repository
      Shortage.Repo,
      # Start the endpoint when the application starts
      ShortageWeb.Endpoint
      # Starts a worker by calling: Shortage.Worker.start_link(arg)
      # {Shortage.Worker, arg},
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Shortage.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    ShortageWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/shortage/redirects.ex
defmodule Shortage.Redirects do
  @moduledoc """
  The Redirects context.
  """

  import Ecto.Query, warn: false
  alias Shortage.Repo

  alias Shortage.Redirects.Link
  alias Shortage.Redirects.Visit

  @doc """
  Returns the list of links.

  ## Examples

      iex> list_links()
      [%Link{}, ...]

  """
  def list_links do
    Repo.all(Link)
  end

  def list_links_with_visits do
    Repo.all(
      from link in Link,
        left_join: visit in assoc(link, :visits),
        group_by: link.id,
        select_merge: %{visit_count: sum(fragment("coalesce(?,0)", visit.count))}
    )
  end

  @doc """
  Gets a single link.

  Raises `Ecto.NoResultsError` if the Link does not exist.

  ## Examples

      iex> get_link!(123)
      %Link{}

      iex> get_link!(456)
      ** (Ecto.NoResultsError)

  """
  def get_link!(id) do
    Repo.one!(
      from link in Link,
        left_join: visit in assoc(link, :visits),
        group_by: link.id,
        where: link.id == ^id,
        select_merge: %{visit_count: sum(fragment("coalesce(?,0)", visit.count))}
    )
  end

  def get_link_visits(id) do
    Repo.all(from v in Visit, order_by: :visited_on, where: v.link_id == ^id)
  end

  def get_link_by_short!(short), do: Repo.get_by!(Link, short: short)

  @doc """
  Creates a link.

  ## Examples

      iex> create_link(%{field: value})
      {:ok, %Link{}}

      iex> create_link(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_link(attrs \\ %{}) do
    %Link{}
    |> Link.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a link.

  ## Examples

      iex> update_link(link, %{field: new_value})
      {:ok, %Link{}}

      iex> update_link(link, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_link(%Link{} = link, attrs) do
    link
    |> Link.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a Link.

  ## Examples

      iex> delete_link(link)
      {:ok, %Link{}}

      iex> delete_link(link)
      {:error, %Ecto.Changeset{}}

  """
  def delete_link(%Link{} = link) do
    Repo.delete(link)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking link changes.

  ## Examples

      iex> change_link(link)
      %Ecto.Changeset{source: %Link{}}

  """
  def change_link(%Link{} = link) do
    Link.changeset(link, %{})
  end

  alias Shortage.Redirects.Visit

  @doc """
  Returns the list of visits.

  ## Examples

      iex> list_visits()
      [%Visit{}, ...]

  """
  def list_visits do
    Repo.all(Visit)
  end

  @doc """
  Gets a single visit.

  Raises `Ecto.NoResultsError` if the Visit does not exist.

  ## Examples

      iex> get_visit!(123)
      %Visit{}

      iex> get_visit!(456)
      ** (Ecto.NoResultsError)

  """
  def get_visit!(id), do: Repo.get!(Visit, id)

  @doc """
  Upserts the visit count for a link.

  """
  def increment_visit(link) do
    Repo.insert(%Visit{link_id: link.id, visited_on: Date.utc_today(), count: 1},
      conflict_target: [:link_id, :visited_on],
      on_conflict: [inc: [count: 1]]
    )
  end

  def visits_count(link) do
    Repo.aggregate(from(p in Visit, where: p.link_id == ^link.id), :sum, :count)
  end
end

lib/shortage/redirects/link.ex
defmodule Shortage.Redirects.Link do
  use Ecto.Schema
  import Ecto.Changeset

  @primary_key {:id, :binary_id, autogenerate: true}
  @foreign_key_type :binary_id
  schema "links" do
    field :short, :string
    field :target, :string

    timestamps()

    field :visit_count, :integer, virtual: true
    has_many :visits, Shortage.Redirects.Visit
  end

  @doc false
  def changeset(link, attrs) do
    link
    |> cast(attrs, [:target, :short])
    |> validate_required([:target, :short])
  end
end

lib/shortage/redirects/visit.ex
defmodule Shortage.Redirects.Visit do
  use Ecto.Schema
  import Ecto.Changeset

  @primary_key {:id, :binary_id, autogenerate: true}
  @foreign_key_type :binary_id
  schema "visits" do
    field :count, :integer
    field :visited_on, :date
    field :link_id, :binary_id

    timestamps()
  end

  @doc false
  def changeset(visit, attrs) do
    visit
    |> cast(attrs, [:visited_on, :count])
    |> validate_required([:visited_on, :count])
  end
end

lib/shortage/repo.ex
defmodule Shortage.Repo do
  use Ecto.Repo,
    otp_app: :shortage,
    adapter: Ecto.Adapters.Postgres
end

lib/shortage_web/controllers/link_controller.ex
defmodule ShortageWeb.LinkController do
  use ShortageWeb, :controller

  alias Shortage.Redirects
  alias Shortage.Redirects.Link

  def index(conn, _params) do
    links = Redirects.list_links_with_visits()
    render(conn, "index.html", links: links)
  end

  def new(conn, _params) do
    changeset = Redirects.change_link(%Link{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"link" => link_params}) do
    strong_short = :crypto.strong_rand_bytes(5) |> Base.url_encode64() |> binary_part(0, 5)
    augmented_params = Map.merge(link_params, %{"short" => strong_short})

    case Redirects.create_link(augmented_params) do
      {:ok, link} ->
        conn
        |> put_flash(:info, "Link created successfully.")
        |> redirect(to: Routes.link_path(conn, :show, link))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    link = Redirects.get_link!(id)

    # TODO: sorting
    visits =
      Shortage.Redirects.get_link_visits(link.id)
      |> Enum.map(fn v -> {v.visited_on, v.count} end)
      |> Map.new()
      |> Poison.encode!()

    render(conn, "show.html", link: link, visits: visits)
  end

  def delete(conn, %{"id" => id}) do
    link = Redirects.get_link!(id)
    {:ok, _link} = Redirects.delete_link(link)

    conn
    |> put_flash(:info, "Link deleted successfully.")
    |> redirect(to: Routes.link_path(conn, :index))
  end
end

lib/shortage_web/controllers/page_controller.ex
defmodule ShortageWeb.PageController do
  use ShortageWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

lib/shortage_web/controllers/shortened_controller.ex
defmodule ShortageWeb.ShortenedController do
  use ShortageWeb, :controller
  alias Shortage.Redirects

  def show(conn, %{"shortened" => shortened}) do
    link = Redirects.get_link_by_short!(shortened)
    Redirects.increment_visit(link)
    redirect(conn, external: link.target)
  end
end

lib/shortage_web/views/error_view.ex
defmodule ShortageWeb.ErrorView do
  use ShortageWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/shortage_web/views/layout_view.ex
defmodule ShortageWeb.LayoutView do
  use ShortageWeb, :view
end

lib/shortage_web/views/link_view.ex
defmodule ShortageWeb.LinkView do
  use ShortageWeb, :view
end

lib/shortage_web/views/page_view.ex
defmodule ShortageWeb.PageView do
  use ShortageWeb, :view
end

lib/shortage_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Shortage | super-fast open source link shortener</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/chartkick/2.3.0/chartkick.min.js" integrity="sha256-pKi+C/L3JqiD10GzkevwyZ+pUZuKi5BxbPZiCg/Val4=" crossorigin="anonymous"></script>
  </head>
  <body>
    <header>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 border-bottom box-shadow bg-brand">
      <h5 class="my-0 mr-md-auto font-weight-normal">
        <a href="/" class="navbar-brand text-light"><strong>Shortage</strong></a>
        <small class="d-none d-md-inline">The blazing-fast link shortener.</small>
      </h5>
    </div>
    </header>
    <main role="main" class="container">
      <%= unless is_nil(get_flash(@conn, :info)) do %>
  <p class="alert alert-success" role="alert"><%= get_flash(@conn, :info) %></p>
<% end %>
<%= unless is_nil(get_flash(@conn, :error)) do %>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
<% end %>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/shortage_web/templates/link/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :target %>
  <%= text_input f, :target %>
  <%= error_tag f, :target %>

  <div>
    <%= submit "Save" %>
  </div>
<% end %>

lib/shortage_web/templates/link/index.html.eex
<h1>Listing Links</h1>

<table>
  <thead>
    <tr>
      <th>Target</th>
      <th>Short</th>
      <th>Count</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for link <- @links do %>
    <tr>
      <td><%= link.target %></td>
      <td><%= Routes.shortened_url(@conn, :show, link.short) %></td>
      <td><%= link.visit_count %></td>
      <td>
        <%= link "Show", to: Routes.link_path(@conn, :show, link) %>
        <%= link "Delete", to: Routes.link_path(@conn, :delete, link), method: :delete, data: [confirm: "Are you sure?"] %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Link", to: Routes.link_path(@conn, :new) %></span>

lib/shortage_web/templates/link/new.html.eex
<h1>New Link</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.link_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.link_path(@conn, :index) %></span>

lib/shortage_web/templates/link/show.html.eex
<h1 class="d-flex justify-content-between flex-column flex-md-row align-bottom">
  <span><%= link @link.target, to: @link.target %></span>
  <span >All-time visits: <strong><%= @link.visit_count %></strong></small>
</h1>

<div class="card my-4 bg-white">
  <div class="card-body">
    <h5 class="card-title">Your shortened link</h5>
    <%=
      link Routes.shortened_url(@conn, :show, @link.short),
      to: Routes.shortened_url(@conn, :show, @link.short)
    %>
  </div>
</div>

<%= raw Chartkick.line_chart @visits, defer: true, discrete: true %>

lib/shortage_web/templates/page/index.html.eex
<div class="col">
  <section class="jumbotron text-center bg-white">
    <h1 class="jumbotron-heading mb-5">Welcome to Shortage!</h1>
    <p class="lead text-muted">
      <%= link 'Shorten a link', to: Routes.link_path(@conn, :new), class: 'btn btn-success' %>
    </p>
  </section>
</div>